export const NEWS_CAROUSEL = {
  AUTO_INTERVAL: 5500,
  RESUME_DELAY: 20000,
} as const;

export const NEWS_SUMMARY_PREVIEW_CHARS = 72;

export const PROJECTS_EXPAND_MS = 580;
export const PROJECTS_CONTENT_REVEAL_RATIO = 0.38;
export const PROJECTS_CONTENT_REVEAL_DELAY = PROJECTS_EXPAND_MS * PROJECTS_CONTENT_REVEAL_RATIO;

export const SWIPE_THRESHOLD = 40;
